POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"nhakhoa02@gmail.com",
    "username": "nhakhoa02",
    "password": "123456"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "nhakhoa01",
    "password": "123456"
}

###
GET http://localhost:5000/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODIzODExNzgwYjYzMzU4YTc0NTQ4MGQiLCJpYXQiOjE3NDcyMTgwNDgsImV4cCI6MTc0NzIxODk0OH0.b5hX6StvokhBj3bhHL_0g67SHoOVaVNLEo8yChXoPyA

{
    "id": "6823811780b63358a745480d"
}

###
POST http://localhost:5000/events/68246ee613ad085a0f8a7e74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODIzODExNzgwYjYzMzU4YTc0NTQ4MGQiLCJpYXQiOjE3NDcyMTgwNDgsImV4cCI6MTc0NzIxODk0OH0.b5hX6StvokhBj3bhHL_0g67SHoOVaVNLEo8yChXoPyA
Content-Type: application/json

{
    "title": "event 5",
    "description": "event 1 description",
    "date": "2023-10-01T00:00:00Z",
    "categoryId": "1"
}

###
POST http://localhost:5000/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODIzODExNzgwYjYzMzU4YTc0NTQ4MGQiLCJpYXQiOjE3NDcyMjUzMDUsImV4cCI6MTc0NzIyNjIwNX0.61yCyQYyZszmXPC4p0B7KZ6P_yvs13aq8gC0QMbnwds
Content-Type: application/json

{
    "url": "www.example.com",
    "type": "avatar"
}