name: Frontend Code Quality Check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run-quality-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies
        run: npm ci
        working-directory: frontend/
      - name: Check Linting rules
        run: npm run lint:test-all
        working-directory: frontend/
      - name: Check Formatting rules
        run: npm run format:test-all
        working-directory: frontend/
